### ISSUE TITLE
Unresolved reference: ClusterManager when using the Kotlin library for maps utilities

### ISSUE THREAD

**Issue by michaeltheodore1984** [googlemaps/android-maps-ktx#161]
Hello

I'm trying to use the Google Maps Utilities Library for Kotlin to use marker clustering.

I added these two lines to my _build.gradle_ file:

```
implementation 'com.google.maps.android:maps-utils-ktx:3.1.0'
implementation 'com.google.maps.android:android-maps-utils:2.2.6'
```

Then I'm trying to create a ClusterManager in MainActivity:

private lateinit var clusterManager: ClusterManager<MyItem>

I am getting the error :

Unresolved reference: ClusterManager

If I downgrade the utilities library to version 2.2.5 the error disappears and everything works but I get another error, something to do with marker collection setOnInfoWindowAdapter.

Please help.

**Comment by arriolac** [comment]
Hi @michaeltheodore1984, I recently just published version 2.2.6 of the Utility Library. You're error is likely due to the the 2.2.6 artifact missing so give it a few minutes until it shows up on maven central.

As far as downgrading to 2.2.5, I think you are referring to a warning and not an error. Is that correct? Can you share the exact warning/error you received?

**Comment by michaeltheodore1984** [comment]
Hi @arriolac 

When I'm using version 2.2.5 of the Utility Library I get the following error:

![marker_clustering_error_android_studio](https://user-images.githubusercontent.com/22627927/133519614-ccaf7816-63ac-416d-b4d3-43197ba34f25.png)

**Comment by arriolac** [comment]
That error appears to be a Kotlin bug. See https://github.com/googlemaps/android-maps-utils/issues/919#issuecomment-876521856
